name: Validate Submissions

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install kaggle numpy

      - name: Set up Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download competition data
        run: |
          kaggle competitions download -c google-code-golf-2025 -p ./data

      - name: Unzip competition files into problems/
        run: |
          mkdir -p problems
          unzip -o ./data/google-code-golf-2025.zip -d ./problems

      - name: Validate submissions
        run: python validate.py
