name: Validate Submissions

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install kaggle numpy

      - name: Download competition data
         env:
           KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
           KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
         run: |
           kaggle competitions download -c google-code-golf-2025 -p ./data

      - name: Unzip competition files into problems/
        run: |
          mkdir -p problems
          unzip -o ./data/google-code-golf-2025.zip -d ./problems

      - name: Validate submissions
        run: python validate.py
